name: Node Package CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: npm install and build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true

  test:
    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    steps:

      - name: npm test
        run: npm test
        env:
          CI: true


